name: CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'Dockerfile'
      - 'src/**'
      - 'VERSION'
      - 'entrypoint.sh'
env:
  BRANCH: ${{ github.ref_name }}
  HASH: ${{ github.sha }}
  REGISTRY: ghcr.io/${{ github.repository }}
  SNAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Docker image
      run: |
        docker buildx build --push -t ${{ env.REGISTRY }}:${{ env.BRANCH }}-${{ env.HASH }} .
