name: CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'Dockerfile'
      - 'src/**'
      - 'VERSION'
      - 'entrypoint.sh'
env:
  BRANCH: ${{ github.ref_name }}
  HASH: ${{ github.sha }}
  REGISTRY: ghcr.io/${{ github.repository }}
  SNAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jdrouet/docker-with-buildx:stable
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: apk add --update bash coreutils tar make git

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set up Docker Buildx
      run: docker buildx create --name mybuilder --use --bootstrap

    - name: Build and Push Docker image
      run: |
        docker buildx build --push -t ${{ env.REGISTRY }}/my-image:${{ env.BRANCH }}-${{ env.HASH }} .
