name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: jdrouet/docker-with-buildx:stable

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: apk add --update bash coreutils tar make git
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: make buildx
